sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
  - '4'
python:
  - "2.7"
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user mkdocs
  - npm install -g npm
before_script :
  - npm install -g grunt-cli
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
