language : node_js
node_js :
    - "0.8"
    - "0.10"
    - "0.12"
    - "4"
    - "5"
python:
    - "2.7"
before_install:
    # Workaround for missing support of multiple languages in Travis;
    # Luckily, root sees python and pip executables and can add mkdocs
    - sudo pip install mkdocs
    - npm install -g npm
before_script :
    - npm install -g grunt-cli
after_script:
    - npm run coveralls
