language : node_js
node_js :
    - "0.8"
    - "0.10"
    - "0.12"
    - "4"
    - "5"
    - "6"
python:
    - "2.7"
before_install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --user mkdocs
    - npm install -g npm
before_script :
    - npm install -g grunt-cli
sudo: false
