sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
python:
  - "2.7"
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user mkdocs
before_script :
  - npm install -g grunt-cli
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
